plugins {
    id 'java-library'
}

group 'com.juanmuscaria'
version '1.1.0'

dependencies {
    implementation platform("com.fasterxml.jackson:jackson-bom:2.21.7")
    implementation "com.fasterxml.jackson.core:jackson-core"
    implementation "com.fasterxml.jackson.core:jackson-annotations"
    implementation "com.fasterxml.jackson.core:jackson-databind"

    implementation 'com.jetbrains.intellij.java:java-gui-forms-rt:233.13135.104'
    implementation 'com.formdev:flatlaf:3.4.1'
    implementation 'com.juanmuscaria:autumn-messages:1.1-SNAPSHOT'
    implementation 'com.juanmuscaria:autumn-resources:1.1-SNAPSHOT'
}

allprojects {
    group = rootProject.group
    version = rootProject.version

    pluginManager.withPlugin('java') {
        repositories {
            mavenCentral()
            maven {
                name = 'intellij-repository'
                url = 'https://www.jetbrains.com/intellij-repository/releases/'
            }
            maven {
                name = "juanmuscaria"
                url = "https://github.com/juanmuscaria/maven/raw/master"
                metadataSources.ignoreGradleMetadataRedirection()
            }

        }

        configurations {
            compileOnly {
                extendsFrom annotationProcessor
            }
        }

        // Jabel stuff, compile with new java features while targeting java 8
        dependencies {
            annotationProcessor 'com.github.bsideup.jabel:jabel-javac-plugin:0.4.2'
            annotationProcessor 'org.projectlombok:lombok:1.18.30'
            testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.1'
            testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.1'
        }

        tasks.withType(org.gradle.api.tasks.compile.JavaCompile).configureEach {
            options.encoding = 'UTF-8'
        }

        configure([tasks.compileJava]) {
            sourceCompatibility = 17 // for the IDE support
            options.release = 8

            javaCompiler = javaToolchains.compilerFor {
                languageVersion = JavaLanguageVersion.of(17)
            }
        }

        compileTestJava {
            sourceCompatibility = targetCompatibility = 8
        }

        test {
            useJUnitPlatform()
            javaLauncher = javaToolchains.launcherFor {
                languageVersion = JavaLanguageVersion.of(8)
            }
        }

    }

    pluginManager.withPlugin('application') {
        run {
            javaLauncher = javaToolchains.launcherFor {
                languageVersion = JavaLanguageVersion.of(8)
            }
        }
    }
}
