plugins {
    id 'application'
    id "com.github.johnrengelman.shadow" version "8.1.1"
}

dependencies {
    implementation project(":standalone")
    implementation project(":modlauncher")
    implementation project(":launchwrapper")
}



jar {
    manifest {
        attributes([
                "TweakClass"            : "com.juanmuscaria.modpackdirector.launchwrapper.ModpackDirectorTweaker",
                "TweakOrder"            : Integer.MIN_VALUE,
                "Specification-Title"   : "ModDirector",
                "Specification-Vendor"  : "Janrupf",
                "Specification-Version" : 1,
                "Implementation-Title"  : "ModpackDirectorUniversal",
                "Implementation-Vendor" : "juanmuscaria",
                "Implementation-Version": archiveVersion.get()
        ])
    }
}

build {
    dependsOn(shadowJar)
}

shadowJar {
    archiveBaseName = 'ContentsDirector'
    exclude('META-INF/versions/**')
    mergeServiceFiles()
    relocate('com.fasterxml.jackson', 'com.juanmuscaria.modpackdirector.shadow.jackson')
}

application {
    mainClass = 'net.jan.moddirector.standalone.ModDirectorStandalone'
}

test {
    dependsOn shadowJar
    systemProperty "contentsDirector.shadowJar", shadowJar.archiveFile.get().asFile.absolutePath
}
